### ISSUE TITLE
Fazer conexão com Banco de Dados

### ISSUE THREAD

**Issue by LeonardoIT** [ArthurCefet/CRUD2019_CEFET#3]

**Comment by ArthurCefet** [comment]
Vou baixar a API Sequelize no backend, com esse comando : 
* npm install --save sequelize

vou criar uma estrutura de pasta no backend, e deixar as informaçoes relacionadas ao bd na pasta model, o arquivo vai ta incompleto pq  nao tem o bd ainda.

**Comment by ArthurCefet** [comment]
Não esquece de dar pull no git para vcs puxarem os arquivos q eu fiz 
💃

**Comment by ArthurCefet** [comment]
FEITO
!!!!
